//! Tauri command handlers
//!
//! These commands are called from the React frontend via Tauri's invoke() API.
//! They act as thin wrappers around the citadel-api functionality.
#![allow(clippy::too_many_arguments)]

mod activity;
mod amm;
mod bridge;
mod burn;
mod dexy;
mod explorer;
mod hodlcoin;
mod lending;
mod mewlock;
mod node;
mod sigmafi;
mod sigmausd;
mod signing;
mod utxo;
mod wallet;

// Wildcard re-exports needed so tauri::generate_handler! can see
// the hidden __cmd__* symbols generated by #[tauri::command].
pub use activity::*;
pub use amm::*;
pub use bridge::*;
pub use burn::*;
pub use dexy::*;
pub use explorer::*;
pub use hodlcoin::*;
pub use lending::*;
pub use mewlock::*;
pub use node::*;
pub use sigmafi::*;
pub use sigmausd::*;
pub use signing::*;
pub use utxo::*;
pub use wallet::*;

/// Parse user UTXOs from JSON values into EIP-12 input boxes.
///
/// Used by all protocol build commands that receive UTXOs from the frontend.
pub fn parse_eip12_utxos(
    utxos: Vec<serde_json::Value>,
) -> Result<Vec<ergo_tx::Eip12InputBox>, String> {
    let parsed: Vec<ergo_tx::Eip12InputBox> = utxos
        .into_iter()
        .map(|v| serde_json::from_value(v).map_err(|e| format!("Invalid UTXO format: {}", e)))
        .collect::<Result<Vec<_>, _>>()?;

    if parsed.is_empty() {
        return Err("No UTXOs provided".to_string());
    }

    Ok(parsed)
}
