//! Tauri command handlers
//!
//! These commands are called from the React frontend via Tauri's invoke() API.
//! They act as thin wrappers around the citadel-api functionality.
#![allow(clippy::too_many_arguments)]

mod activity;
mod amm;
mod burn;
mod dexy;
mod ergopad_recovery;
mod explorer;
mod hodlcoin;
mod lending;
mod mewlock;
mod node;
mod sigmafi;
mod sigmausd;
mod signing;
mod utxo;
mod wallet;

// Wildcard re-exports needed so tauri::generate_handler! can see
// the hidden __cmd__* symbols generated by #[tauri::command].
pub use activity::*;
pub use amm::*;
pub use burn::*;
pub use dexy::*;
pub use ergopad_recovery::*;
pub use explorer::*;
pub use hodlcoin::*;
pub use lending::*;
pub use mewlock::*;
pub use node::*;
pub use sigmafi::*;
pub use sigmausd::*;
pub use signing::*;
pub use utxo::*;
pub use wallet::*;

/// Parse user UTXOs from JSON values into EIP-12 input boxes.
///
/// Used by all protocol build commands that receive UTXOs from the frontend.
pub fn parse_eip12_utxos(
    utxos: Vec<serde_json::Value>,
) -> Result<Vec<ergo_tx::Eip12InputBox>, String> {
    let parsed: Vec<ergo_tx::Eip12InputBox> = utxos
        .into_iter()
        .map(|v| serde_json::from_value(v).map_err(|e| format!("Invalid UTXO format: {}", e)))
        .collect::<Result<Vec<_>, _>>()?;

    if parsed.is_empty() {
        return Err("No UTXOs provided".to_string());
    }

    Ok(parsed)
}

/// Extract a 33-byte public key hex from a P2PK ErgoTree hex string.
///
/// Expects the ErgoTree to start with `0008cd` followed by 66 hex chars (33 bytes).
pub fn extract_p2pk_pubkey(ergo_tree: &str) -> Result<String, String> {
    if ergo_tree.starts_with("0008cd") && ergo_tree.len() >= 72 {
        Ok(ergo_tree[6..72].to_string())
    } else {
        Err(format!(
            "Cannot extract public key from ErgoTree: expected P2PK tree starting with '0008cd', got '{}'",
            &ergo_tree[..std::cmp::min(12, ergo_tree.len())]
        ))
    }
}

/// Extension trait to convert any `Result<T, E: Display>` to `Result<T, String>`.
///
/// Replaces the repeated `.map_err(|e| e.to_string())` pattern across all commands.
pub trait StrErr<T> {
    fn str_err(self) -> Result<T, String>;
}

impl<T, E: std::fmt::Display> StrErr<T> for Result<T, E> {
    fn str_err(self) -> Result<T, String> {
        self.map_err(|e| e.to_string())
    }
}
